### ISSUE TITLE
Error when trying to save Tokyo Revengers bin file.

### ISSUE THREAD

**Issue by FatalXFury** [cfogrady/DIM-Modifier#42] opened 2023-06-16 09:35 UTC
like the title says. I backed up my Tokyo Revengers BEM. I opened it with Dim Modifier and tried to add custom backgrounds. An error popped up when trying to save the bin file. Ive changed backgrounds before and never faced an issue with my 25th BEM. I was curious if i would get the same error message if i didn't replace anything at all. Sure enough, the same error message popped up even though i loaded the raw, untampered bin file and tried saving it.
![Capture](https://github.com/cfogrady/DIM-Modifier/assets/88270571/712ce8ae-cb54-463f-8e4a-5ed11a77b39e)

**Comment by cfogrady** [comment] 2023-06-21 02:06
This is a duplicate of https://github.com/cfogrady/DIM-Modifier/issues/24
This is fixed in 2.1 branch code, but hasn't been released in a binary yet.

**Closed** 2023-12-22 02:04 UTC
Labels: duplicate
